Support other language than english
kellerza/pysma pull request #117
Opened 2023-02-26 15:39 UTC by frimtec

Would like to use pysma with another language than the hardcoded "en-US".

2023-02-27 07:12 UTC, frimtec commented
Fixed all code layout issues.

2023-02-27 09:17 UTC, frimtec commented
Fixed all code layout issues in new test.

2023-02-27 10:00 UTC, rklomp requested changes
Thanks for the pull request! This looks like a great addition.
See my comment on the test.



Ps. Run 1 pre-commit install1 to set up the git hook scripts.

2023-02-27 10:04 UTC, frimtec commented on tests/test_init.py
> +        )
Thanks @rklomp for your seugesstion. Makes totally sence, will change that ASAP.

2023-02-27 10:19 UTC, merged

2023-03-04 12:21 UTC, frimtec commented
Dear @rklomp, would it be possible to make a new release of pysma with the merged change?
My idea is to integrate the new language feature into home assistant.
Many thanks in advance
frimtec

2023-03-04 14:55 UTC, rklomp commented
Done! Bumped to 0.7.4